draw_config:
  key_h: 80
  combo_w: 48
  combo_h: 70.0
  key_rx: 6.0
  key_ry: 6.0
  inner_pad_w: 5.0
  inner_pad_h: 5.0
  outer_pad_w: 10.0
  outer_pad_h: 40.0
  line_spacing: 1.2
  arc_radius: 20.0
  arc_scale: 1
  append_colon_to_layer_header: false
  small_pad: 17.0
  combo_diagrams_scale: 4
  draw_key_sides: true
  key_side_pars:
    rel_h: 10
  svg_style: | # css
    /* reusable color variables. palette taken from https://github.com/rebelot/kanagawa.nvim */
    :root {
        --background-color: #1F1F28;
        --foreground-color: #E6C384;
        --held-color: #98BB6C;
        --shifted-color: #DCD7BA;
        --layer-color: #C34043;
        --combo-color: #938AA9;
        --keycap-color: #727169;
        --hold-fill-color: var(--background-color);

        fill: var(--foreground-color);
        background-color: var(--background-color);
        font-family: JetBrainsMono,NerdFontsSymbols Nerd Font;
        font-size: 13px;
        text-anchor: middle;
        dominant-baseline: middle;
    }

    .combo-separate {
        font-size: 36px;
    }

    .vertical_combo {
        font-size: 15px;
    }

    .layer_switch.tap {
        fill: var(--layer-color);
    }

    rect {
        fill: var(--background-color);
        stroke: var(--keycap-color);
        stroke-width: 0.5;
    }

    .label {
        font-size: 24px;
        text-anchor: start;
        fill: var(--layer-color);
        paint-order: stroke;
    }

    .shifted {
        dominant-baseline: auto;
        fill: var(--shifted-color);
    }

    .hold {
        fill: var(--held-color);
    }

    [class*="layer-combopos"] {
        --hold-fill-color: var(--combo-color);
    }

    rect.held {
        fill: var(--hold-fill-color);
        stroke: var(--held-color);
    }

    path.combo, path.combo-separate {
        stroke-width: 0.5;
        stroke: var(--combo-color);
        fill: none;
    }

    rect.combo, rect.combo-separate {
        stroke: var(--combo-color);
        stroke-width: 1.0;
    }

    rect.vertical_combo, rect.diagonal_combo {
        stroke: none;
        fill: none;
    }

